version: "3.9"
services:
  portfolio:
    build: .
    image: portfolio:latest
    ports:
      - "5051:5051"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:5051"
    volumes:
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys
    restart: unless-stopped

volumes:
  dataprotection-keys:
